# Use new trusty images, should yield newer compilers and packages
sudo:               true
dist:               trusty
language:           cpp

matrix:
  include:
    - compiler:     gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
          - COMPILERCXX=g++-5
          - COMPILERC=gcc-5
          - CGROUP_SUP=TRUE
    - compiler:     gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
          - COMPILERCXX=g++-5
          - COMPILERC=gcc-5
          - CGROUP_SUP=FALSE
    - compiler:     gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERCXX=g++-6
          - COMPILERC=gcc-6
          - CGROUP_SUP=TRUE
    - compiler:     gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERCXX=g++-6
          - COMPILERC=gcc-6
          - CGROUP_SUP=FALSE
    - compiler:     clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERC=clang
          - COMPILERCXX=clang++
          - CLANGV=3.9.1
          - CGROUP_SUP=TRUE
    - compiler:     clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERC=clang
          - COMPILERCXX=clang++
          - CLANGV=3.9.1
          - CGROUP_SUP=FALSE
    - compiler:     clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERC=clang
          - COMPILERCXX=clang++
          - CLANGV=4.0.1
          - CGROUP_SUP=TRUE
          - RUNCLANGTIDY=TRUE
    - compiler:     clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERC=clang
          - COMPILERCXX=clang++
          - CLANGV=4.0.1
          - CGROUP_SUP=FALSE
          - RUNCLANGTIDY=TRUE

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - mkdir $HOME/clang+llvm
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - if [ -n "$CLANGV" ]; then wget http://llvm.org/releases/$CLANGV/clang+llvm-$CLANGV-x86_64-linux-gnu-debian8.tar.xz -O $HOME/clang+llvm.tar.xz; fi
  - if [ -n "$CLANGV" ]; then tar xf $HOME/clang+llvm.tar.xz -C $HOME/clang+llvm --strip-components 1; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=true -DCMAKE_CXX_COMPILER=$COMPILERCXX -DCMAKE_C_COMPILER=$COMPILERC -DBUILD_CGROUP_SUPPORT=$CGROUP_SUP -DCMAKE_INSTALL_PREFIX=/tmp/ ..
  - make
  - cd ..
  - if [ -n "$RUNCLANGTIDY" ]; then git ls-files '*.cpp' | xargs -P 1 -I{} clang-tidy -header-filter=.* -p build {}; fi
